// examples/vue-showcase/src/app/demo/DemoSection.vue
<script setup lang="ts">
defineProps<{
  title: string
  description?: string
}>()
</script>

<template>
  <section class="showcase-demo-section">
    <header class="showcase-demo-section-header">
      <h2 class="showcase-section-title">{{ title }}</h2>
      <p v-if="description" class="showcase-card-description">
        {{ description }}
      </p>
    </header>

    <div class="showcase-demo-section-body">
      <slot />
    </div>
  </section>
</template>

// examples/react-showcase/src/app/demo/DemoSection.tsx
import type { ReactNode } from 'react'

export function DemoSection(props: {
  title: string
  description?: string
  children: ReactNode
}) {
  return (
    <section className="showcase-demo-section">
      <header className="showcase-demo-section-header">
        <h2 className="showcase-section-title">{props.title}</h2>
        {props.description ? (
          <p className="showcase-card-description">{props.description}</p>
        ) : null}
      </header>

      <div className="showcase-demo-section-body">{props.children}</div>
    </section>
  )
}
