// examples/vue-showcase/src/app/AppShell.vue
<script setup lang="ts">
import Sidebar from './Sidebar.vue'
import Topbar from './Topbar.vue'
</script>

<template>
  <div class="showcase-shell">
    <Topbar />

    <div class="showcase-layout">
      <Sidebar />

      <main class="showcase-content">
        <slot />
      </main>
    </div>
  </div>
</template>

// examples/react-showcase/src/app/AppShell.tsx
import type { ReactNode } from 'react'

import { Sidebar } from './Sidebar'
import { Topbar } from './Topbar'

export function AppShell(props: { children: ReactNode }) {
  return (
    <div className="showcase-shell">
      <Topbar />

      <div className="showcase-layout">
        <Sidebar />
        <main className="showcase-content">{props.children}</main>
      </div>
    </div>
  )
}
