// examples/react-showcase/src/app/demo/DemoPage.tsx
import type { ReactNode } from 'react'

export function DemoPage(props: {
  eyebrow?: string
  title: string
  description: string
  meta?: ReactNode
  children: ReactNode
}) {
  return (
    <div className="showcase-page">
      <header className="showcase-page-header">
        {props.eyebrow ? (
          <p className="showcase-eyebrow">{props.eyebrow}</p>
        ) : null}

        <h1 className="showcase-title">{props.title}</h1>
        <p className="showcase-description">{props.description}</p>

        {props.meta ? (
          <div className="showcase-page-meta">{props.meta}</div>
        ) : null}
      </header>

      <div className="showcase-demo-stack">{props.children}</div>
    </div>
  )
}

// examples/vue-showcase/src/app/demo/DemoPage.vue
<script setup lang="ts">
defineProps<{
  eyebrow?: string
  title: string
  description: string
}>()
</script>

<template>
  <div class="showcase-page">
    <header class="showcase-page-header">
      <p v-if="eyebrow" class="showcase-eyebrow">{{ eyebrow }}</p>
      <h1 class="showcase-title">{{ title }}</h1>
      <p class="showcase-description">{{ description }}</p>

      <div v-if="$slots.meta" class="showcase-page-meta">
        <slot name="meta" />
      </div>
    </header>

    <div class="showcase-demo-stack">
      <slot />
    </div>
  </div>
</template>
