// examples/react-showcase/src/app/demo/PropTable.tsx
export interface PropTableRow {
  name: string
  type: string
  defaultValue?: string
  description: string
}

export function PropTable(props: { rows: PropTableRow[] }) {
  if (props.rows.length === 0) {
    return <div className="showcase-empty">No props documented yet.</div>
  }

  return (
    <div className="showcase-table-wrap">
      <table className="showcase-table">
        <thead>
          <tr>
            <th>Prop</th>
            <th>Type</th>
            <th>Default</th>
            <th>Description</th>
          </tr>
        </thead>

        <tbody>
          {props.rows.map(row => (
            <tr key={row.name}>
              <td>
                <code>{row.name}</code>
              </td>
              <td>
                <code>{row.type}</code>
              </td>
              <td>
                {row.defaultValue ? <code>{row.defaultValue}</code> : '—'}
              </td>
              <td>{row.description}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

// examples/vue-showcase/src/app/demo/PropTable.vue
<script setup lang="ts">
export interface PropTableRow {
  name: string
  type: string
  defaultValue?: string
  description: string
}

defineProps<{
  rows: PropTableRow[]
}>()
</script>

<template>
  <div v-if="rows.length === 0" class="showcase-empty">
    No props documented yet.
  </div>

  <div v-else class="showcase-table-wrap">
    <table class="showcase-table">
      <thead>
        <tr>
          <th>Prop</th>
          <th>Type</th>
          <th>Default</th>
          <th>Description</th>
        </tr>
      </thead>

      <tbody>
        <tr v-for="row in rows" :key="row.name">
          <td>
            <code>{{ row.name }}</code>
          </td>
          <td>
            <code>{{ row.type }}</code>
          </td>
          <td>
            <code v-if="row.defaultValue">{{ row.defaultValue }}</code>
            <span v-else>—</span>
          </td>
          <td>{{ row.description }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
