// examples/react-showcase/src/app/demo/StateMatrix.tsx
export function StateMatrix(props: { states: string[] }) {
  if (props.states.length === 0) {
    return <div className="showcase-empty">No states documented yet.</div>
  }

  return (
    <div className="showcase-state-matrix">
      {props.states.map(state => (
        <div key={state} className="showcase-state-cell">
          <span className="showcase-badge">{state}</span>
          <div className="showcase-state-preview">
            <span>{state}</span>
          </div>
        </div>
      ))}
    </div>
  )
}

// examples/vue-showcase/src/app/demo/StateMatrix.vue
<script setup lang="ts">
defineProps<{
  states: string[]
}>()
</script>

<template>
  <div v-if="states.length === 0" class="showcase-empty">
    No states documented yet.
  </div>

  <div v-else class="showcase-state-matrix">
    <div v-for="state in states" :key="state" class="showcase-state-cell">
      <span class="showcase-badge">{{ state }}</span>
      <div class="showcase-state-preview">
        <span>{{ state }}</span>
      </div>
    </div>
  </div>
</template>
