// examples/react-showcase/src/app/demo/ThemeTokenPreview.tsx
export function ThemeTokenPreview(props: { tokens: string[] }) {
  if (props.tokens.length === 0) {
    return <div className="showcase-empty">No theme tokens documented yet.</div>
  }

  return (
    <div className="showcase-token-grid">
      {props.tokens.map(token => (
        <div key={token} className="showcase-token-card">
          <span className="showcase-badge">{token}</span>
          <div
            className="showcase-token-swatch"
            style={{
              background: `hsl(var(--${token}))`,
            }}
          />
        </div>
      ))}
    </div>
  )
}

// examples/vue-showcase/src/app/demo/ThemeTokenPreview.vue
<script setup lang="ts">
defineProps<{
  tokens: string[]
}>()
</script>

<template>
  <div v-if="tokens.length === 0" class="showcase-empty">
    No theme tokens documented yet.
  </div>

  <div v-else class="showcase-token-grid">
    <div v-for="token in tokens" :key="token" class="showcase-token-card">
      <span class="showcase-badge">{{ token }}</span>
      <div
        class="showcase-token-swatch"
        :style="{ background: `hsl(var(--${token}))` }"
      />
    </div>
  </div>
</template>
