// examples/react-showcase/src/routes/PlaygroundPage.tsx
export function PlaygroundPage() {
  return (
    <div className="showcase-page">
      <header className="showcase-page-header">
        <p className="showcase-eyebrow">Playground</p>
        <h1 className="showcase-title">Production composition playground</h1>
        <p className="showcase-description">
          This route will host production-like composed scenarios in later
          phases: admin dashboard, settings form and project creation flow.
        </p>
      </header>

      <section className="showcase-grid showcase-grid-3">
        <Scenario
          title="Admin dashboard"
          description="Cards, badges, progress, alerts and icons."
        />
        <Scenario
          title="Settings form"
          description="Labels, inputs, selects, checkboxes, switches and validation."
        />
        <Scenario
          title="Project creation"
          description="Dialog, form controls, tooltips and event logs."
        />
      </section>
    </div>
  )
}

function Scenario(props: { title: string; description: string }) {
  return (
    <div className="showcase-card">
      <h2 className="showcase-card-title">{props.title}</h2>
      <p className="showcase-card-description">{props.description}</p>
      <span className="showcase-badge">planned</span>
    </div>
  )
}

// examples/vue-showcase/src/routes/PlaygroundPage.vue
<script setup lang="ts">
const scenarios = [
  {
    title: 'Admin dashboard',
    description: 'Cards, badges, progress, alerts and icons.',
  },
  {
    title: 'Settings form',
    description:
      'Labels, inputs, selects, checkboxes, switches and validation.',
  },
  {
    title: 'Project creation',
    description: 'Dialog, form controls, tooltips and event logs.',
  },
]
</script>

<template>
  <div class="showcase-page">
    <header class="showcase-page-header">
      <p class="showcase-eyebrow">Playground</p>
      <h1 class="showcase-title">Production composition playground</h1>
      <p class="showcase-description">
        This route will host production-like composed scenarios in later phases:
        admin dashboard, settings form and project creation flow.
      </p>
    </header>

    <section class="showcase-grid showcase-grid-3">
      <div
        v-for="scenario in scenarios"
        :key="scenario.title"
        class="showcase-card"
      >
        <h2 class="showcase-card-title">{{ scenario.title }}</h2>
        <p class="showcase-card-description">{{ scenario.description }}</p>
        <span class="showcase-badge">planned</span>
      </div>
    </section>
  </div>
</template>
