// packages/registry/templates/vue/button.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Button as ButtonPrimitive } from '@zeus-web/button/vue'

import { cn } from '@/lib/cn'

type ButtonVariant =
  | 'default'
  | 'primary'
  | 'secondary'
  | 'outline'
  | 'ghost'
  | 'danger'

type ButtonSize = 'sm' | 'md' | 'lg' | 'icon'

const props = withDefaults(
  defineProps<{
    variant?: ButtonVariant
    size?: ButtonSize
    class?: string
    disabled?: boolean
  }>(),
  {
    variant: 'default',
    size: 'md',
    class: '',
    disabled: false,
  },
)

const buttonVariantClasses: Record<ButtonVariant, string> = {
  default:
    'border border-[hsl(var(--zeus-border))] bg-[hsl(var(--zeus-background))] text-[hsl(var(--zeus-foreground))] hover:bg-[hsl(var(--zeus-accent))] hover:text-[hsl(var(--zeus-accent-foreground))]',
  primary:
    'border border-[hsl(var(--zeus-primary))] bg-[hsl(var(--zeus-primary))] text-[hsl(var(--zeus-primary-foreground))] hover:bg-[hsl(var(--zeus-primary)/0.9)]',
  secondary:
    'border border-transparent bg-[hsl(var(--zeus-secondary))] text-[hsl(var(--zeus-secondary-foreground))] hover:bg-[hsl(var(--zeus-secondary)/0.8)]',
  outline:
    'border border-[hsl(var(--zeus-border))] bg-transparent text-[hsl(var(--zeus-foreground))] hover:bg-[hsl(var(--zeus-accent))] hover:text-[hsl(var(--zeus-accent-foreground))]',
  ghost:
    'border border-transparent bg-transparent text-[hsl(var(--zeus-foreground))] hover:bg-[hsl(var(--zeus-accent))] hover:text-[hsl(var(--zeus-accent-foreground))]',
  danger:
    'border border-[hsl(var(--zeus-destructive))] bg-[hsl(var(--zeus-destructive))] text-[hsl(var(--zeus-destructive-foreground))] hover:bg-[hsl(var(--zeus-destructive)/0.9)]',
}

const buttonSizeClasses: Record<ButtonSize, string> = {
  sm: 'h-8 px-3 text-xs',
  md: 'h-9 px-4 text-sm',
  lg: 'h-10 px-6 text-sm',
  icon: 'h-9 w-9 p-0',
}

const classes = computed(() =>
  cn(
    'inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-[var(--zeus-radius-md)] font-medium transition-colors',
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--zeus-ring)/0.45)] focus-visible:ring-offset-2',
    'disabled:pointer-events-none disabled:opacity-50',
    buttonVariantClasses[props.variant],
    buttonSizeClasses[props.size],
    props.class,
  ),
)
</script>

<template>
  <ButtonPrimitive
    :variant="variant"
    :size="size"
    :disabled="disabled"
    :class="classes"
  >
    <slot />
  </ButtonPrimitive>
</template>

// packages/registry/default/button.tsx
import type { VariantProps } from 'class-variance-authority'
import { Button as ButtonPrimitive } from '@zeus-web/button/react'
import { cva } from 'class-variance-authority'
import * as React from 'react'

import { cn } from '@/lib/utils'

const buttonVariants = cva(
  [
    'inline-flex',
    '[&_[data-slot=button]]:inline-flex',
    '[&_[data-slot=button]]:items-center',
    '[&_[data-slot=button]]:justify-center',
    '[&_[data-slot=button]]:gap-2',
    '[&_[data-slot=button]]:whitespace-nowrap',
    '[&_[data-slot=button]]:rounded-md',
    '[&_[data-slot=button]]:text-sm',
    '[&_[data-slot=button]]:font-medium',
    '[&_[data-slot=button]]:transition-colors',
    '[&_[data-slot=button]]:border-0',
    '[&_[data-slot=button]]:appearance-none',
    '[&_[data-slot=button]]:focus-visible:outline-none',
    '[&_[data-slot=button]]:focus-visible:ring-1',
    '[&_[data-slot=button]]:focus-visible:ring-ring',
    '[&_[data-slot=button]]:disabled:pointer-events-none',
    '[&_[data-slot=button]]:disabled:opacity-50',
    '[&_[data-slot=button-prefix]]:inline-flex',
    '[&_[data-slot=button-prefix]]:items-center',
    '[&_[data-slot=button-suffix]]:inline-flex',
    '[&_[data-slot=button-suffix]]:items-center',
  ].join(' '),
  {
    variants: {
      variant: {
        default:
          '[&_[data-slot=button]]:bg-primary [&_[data-slot=button]]:text-primary-foreground [&_[data-slot=button]]:shadow [&_[data-slot=button]]:hover:bg-primary/90',
        primary:
          '[&_[data-slot=button]]:bg-primary [&_[data-slot=button]]:text-primary-foreground [&_[data-slot=button]]:shadow [&_[data-slot=button]]:hover:bg-primary/90',
        secondary:
          '[&_[data-slot=button]]:bg-secondary [&_[data-slot=button]]:text-secondary-foreground [&_[data-slot=button]]:shadow-sm [&_[data-slot=button]]:hover:bg-secondary/80',
        outline:
          '[&_[data-slot=button]]:border [&_[data-slot=button]]:border-input [&_[data-slot=button]]:bg-background [&_[data-slot=button]]:shadow-sm [&_[data-slot=button]]:hover:bg-accent [&_[data-slot=button]]:hover:text-accent-foreground',
        ghost:
          '[&_[data-slot=button]]:bg-transparent [&_[data-slot=button]]:hover:bg-accent [&_[data-slot=button]]:hover:text-accent-foreground',
        danger:
          '[&_[data-slot=button]]:bg-destructive [&_[data-slot=button]]:text-destructive-foreground [&_[data-slot=button]]:shadow-sm [&_[data-slot=button]]:hover:bg-destructive/90',
      },
      size: {
        sm: '[&_[data-slot=button]]:h-8 [&_[data-slot=button]]:rounded-md [&_[data-slot=button]]:px-3 [&_[data-slot=button]]:text-xs',
        md: '[&_[data-slot=button]]:h-9 [&_[data-slot=button]]:px-4 [&_[data-slot=button]]:py-2',
        lg: '[&_[data-slot=button]]:h-10 [&_[data-slot=button]]:rounded-md [&_[data-slot=button]]:px-8',
        icon: '[&_[data-slot=button]]:size-9',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'md',
    },
  },
)

export interface ButtonProps
  extends
    React.ComponentPropsWithoutRef<typeof ButtonPrimitive>,
    VariantProps<typeof buttonVariants> {}

export const Button = React.forwardRef<HTMLElement, ButtonProps>(
  ({ className, variant, size, ...props }, ref) => {
    return (
      <ButtonPrimitive
        ref={ref}
        data-slot="button"
        variant={variant ?? undefined}
        size={size ?? undefined}
        className={cn(buttonVariants({ variant, size }), className)}
        {...props}
      />
    )
  },
)

Button.displayName = 'Button'

export { buttonVariants }
