// examples/react-showcase/src/app/RouteCard.tsx
import { Link } from '@tanstack/react-router'

export function RouteCard(props: {
  to: string
  title: string
  description: string
  badge?: string
}) {
  return (
    <Link to={props.to as string} className="showcase-card">
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          gap: '1rem',
        }}
      >
        <div>
          <h3 className="showcase-card-title">{props.title}</h3>
          <p className="showcase-card-description">{props.description}</p>
        </div>

        {props.badge && <span className="showcase-badge">{props.badge}</span>}
      </div>
    </Link>
  )
}

// examples/vue-showcase/src/app/RouteCard.vue
<script setup lang="ts">
defineProps<{
  to: string
  title: string
  description: string
  badge?: string
}>()
</script>

<template>
  <RouterLink :to="to" class="showcase-card">
    <div style="display: flex; justify-content: space-between; gap: 1rem">
      <div>
        <h3 class="showcase-card-title">{{ title }}</h3>
        <p class="showcase-card-description">{{ description }}</p>
      </div>

      <span v-if="badge" class="showcase-badge">{{ badge }}</span>
    </div>
  </RouterLink>
</template>
